### ISSUE TITLE
Bad arguments for message 'loadbang' to object 'leapmotion'

### ISSUE THREAD

**Issue by agitato816** [grrrr/flext#20]
Hi,

what's this error? how to fix it? it was ok with pd 0.45 but error with 0.47

ubuntu 14.04 64bit
pd 0.47

thanks,
akntk

**Comment by grrrr** [comment]
Hi, it's harmless and supposed to be fixed with the current flext git
version.

Am 07.07.2016 um 12:56 schrieb Jonghyun Kim notifications@github.com:

Hi,

what's this error? how to fix it? it was ok with pd 0.45 but error with 0.47

ubuntu 14.04 64bit
pd 0.47

thanks,
akntk

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/grrrr/flext/issues/20, or mute the thread
https://github.com/notifications/unsubscribe/AAJ-Js4yynmXLdnKq9HfY2XAFHOmPLdSks5qTNtKgaJpZM4JG9vl
.

**Comment by grrrr** [comment]
Just checked, it is indeed resolved.
