### ISSUE TITLE
Questions: maintenance status / support for GEM and Jitter

### ISSUE THREAD

**Issue by smokhov** [grrrr/flext#46]
Hello,

We are looking to writing externals for Jitter (in Max) and GEM (in Pd).
Our library is in C++, so I thought flext would be a good fit.

Questions are:

- is this project still maintained and still can work agains the most recent Max and Pd versions?
- I am also looking for Jitter and GEM examples of externals that compile with this

I saw some forks of this have newer material that is not in this repo so I guess there is still interest in this.

**Comment by grrrr** [comment]
Hi, sorry for responding so late.
The project is still maintained although not quite actively.
It works very well for Pd and not so well for newer Max version since the API has drastically changed. This applies mostly for operations of buffer~s. This should really be overhauled.
I don't know enough about your project to give a recommendation to use flext. Often, with larger framework, the interface to Pd or Max is only a small part, where it is absolutely feasible to just use the official API, see the sound design toolkit (SDT) for example. For Max there is also a kind of official C++ interface.

**Comment by smokhov** [comment]
Thanks for the reply and pointers @grrrr -- I am aware of their proper APIs/SDKs, the issue for us here is to maintain one repo/project vs two :) so I asked.

**Comment by smokhov** [comment]
And the project in question here is OpenISS.
